name: cocamita
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  screenshot: ^3.0.0
  share_plus: ^12.0.2
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icono_cocamita.png"

flutter:
  uses-material-design: true
  fonts:
    - family: PoppinsFonts
      fonts:
        - asset: assets/fonts/poppins_300light.ttf
          weight: 300
        - asset: assets/fonts/poppins_400regular.ttf
          weight: 400
        - asset: assets/fonts/poppins_500medium.ttf
          weight: 500
        - asset: assets/fonts/poppins_600semibold.ttf
          weight: 600
        - asset: assets/fonts/poppins_700bold.ttf
          weight: 700
